### PR TITLE
added current usage query

### PR DESCRIPTION
**Pull request by emilylatouche**
just an initial start of some admin queries. let me know if you have anything you would like me to look into/add.

### CODE REVIEW

**Comment by peteowlett** [comment]
Nice! I have a list too, I'll add them to this branch

**Comment by emilylatouche** [comment]
you will add to the branch then merge back to master?

**Comment by peteowlett** [comment]
Yep - see i can commit and push to the same branch, and they automatically appear here in the PR. When we're both happy with it, we can agree to merge.

As to who should actually press the merge button - opinions vary, but there's no right answer. At deliveroo, so long as the reviewer has added a comment saying `LGTM` (for Looks Good To Me) then anyone can go ahead and merge.

**Comment by peteowlett** [comment]
LGTM

**Pull request merged**
